const typescriptPlugin = require('@typescript-eslint/eslint-plugin');
const angularEslintPlugin = require('@angular-eslint/eslint-plugin');
const angularEslintTemplatePlugin = require('@angular-eslint/eslint-plugin-template');
const prettierPlugin = require('eslint-plugin-prettier');
const importPlugin = require('eslint-plugin-import');
const unusedImportsPlugin = require('eslint-plugin-unused-imports');
const boundariesPlugin = require('eslint-plugin-boundaries');
const tsParser = require('@typescript-eslint/parser');
const angularTemplateParser = require('@angular-eslint/template-parser');
const path = require('path');

module.exports = [
  {
    ignores: [
      'dist/**',
      'node_modules/**',
      'src/app/core/components/icons/lumen-icons.ts', // generated by svg-to-ts
    ],
  },

  // ===================== TS files =====================
  {
    files: ['**/*.ts'],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        project: path.resolve(__dirname, 'tsconfig.app.json'),
        tsconfigRootDir: __dirname,
        createDefaultProgram: true,
        ecmaVersion: 'latest',
        sourceType: 'module',
      },
    },
    plugins: {
      '@typescript-eslint': typescriptPlugin,
      '@angular-eslint': angularEslintPlugin,
      prettier: prettierPlugin,
      import: importPlugin,
      'unused-imports': unusedImportsPlugin,
      boundaries: boundariesPlugin,
    },
    settings: {
      'boundaries/elements': [
        { type: 'bootstrap', pattern: 'src/*.ts' },
        { type: 'root', pattern: 'src/app/*.ts' },
        { type: 'core', pattern: 'src/app/core/**' },
        { type: 'feature', pattern: 'src/app/!(core)/*/**' },
      ],
    },
    rules: {
      // --- Prettier ---
      'prettier/prettier': ['error', { endOfLine: 'auto' }],

      // --- Angular ---
      '@angular-eslint/prefer-standalone': 'error',
      '@angular-eslint/prefer-signals': 'error',
      '@angular-eslint/prefer-on-push-component-change-detection': 'error',
      '@angular-eslint/no-uncalled-signals': 'error',
      '@angular-eslint/no-output-native': 'error',
      '@angular-eslint/no-output-rename': 'error',
      '@angular-eslint/no-input-rename': 'error',
      '@angular-eslint/no-empty-lifecycle-method': 'error',
      '@angular-eslint/use-pipe-transform-interface': 'error',
      '@angular-eslint/component-class-suffix': 'error',
      '@angular-eslint/component-selector': [
        'error',
        { type: 'element', prefix: 'app', style: 'kebab-case' },
      ],
      '@angular-eslint/directive-class-suffix': 'error',
      '@angular-eslint/directive-selector': [
        'error',
        { type: 'attribute', prefix: 'app', style: 'camelCase' },
      ],
      '@angular-eslint/use-lifecycle-interface': 'off',

      // --- TypeScript ---
      '@typescript-eslint/explicit-function-return-type': 'warn',
      '@typescript-eslint/consistent-type-definitions': ['error', 'interface'],
      '@typescript-eslint/dot-notation': 'off',
      '@typescript-eslint/explicit-member-accessibility': ['off'],
      '@typescript-eslint/member-ordering': 'error',
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-empty-function': 'off',
      '@typescript-eslint/no-empty-interface': 'error',
      '@typescript-eslint/no-non-null-assertion': 'error',
      '@typescript-eslint/no-unused-expressions': ['error', { allowTernary: true }],
      '@typescript-eslint/prefer-function-type': 'error',
      '@typescript-eslint/unified-signatures': 'error',
      '@typescript-eslint/no-shadow': ['error', { hoist: 'all' }],
      '@typescript-eslint/prefer-readonly': 'error',
      '@typescript-eslint/parameter-properties': [
        'error',
        { prefer: 'class-property', allow: [] },
      ],

      // --- Unused imports/vars ---
      'no-unused-vars': 'off',
      '@typescript-eslint/no-unused-vars': 'off',
      'unused-imports/no-unused-imports': 'error',
      'unused-imports/no-unused-vars': [
        'error',
        {
          vars: 'all',
          varsIgnorePattern: '^_',
          args: 'after-used',
          argsIgnorePattern: '^_',
        },
      ],

      // --- General ---
      'no-unreachable': 'error',
      'no-console': 'error',
      'no-multiple-empty-lines': ['error', { max: 1, maxEOF: 0 }],
      curly: 'error',
      eqeqeq: ['error', 'smart'],
      'no-bitwise': 'error',
      'no-caller': 'error',
      'no-debugger': 'error',
      'no-empty': 'off',
      'no-eval': 'error',
      'no-fallthrough': 'error',
      'no-new-wrappers': 'error',
      'no-redeclare': 'error',
      'no-throw-literal': 'error',
      'no-undef-init': 'error',
      'no-underscore-dangle': 'off',
      'no-unused-labels': 'error',
      'no-var': 'error',
      'prefer-const': 'error',
      radix: 'error',
      'spaced-comment': ['error', 'never', { line: { markers: ['/'] } }],
      'lines-between-class-members': ['error', 'always', { exceptAfterSingleLine: true }],
      'max-len': ['error', { code: 256 }],

      // --- Imports: порядок ---
      'import/order': [
        'error',
        {
          groups: ['builtin', 'external', 'internal', 'parent', 'sibling', 'index'],
          pathGroups: [
            { pattern: '@angular/**', group: 'external', position: 'before' },
            { pattern: '@core/**', group: 'internal', position: 'after' },
            { pattern: '@main', group: 'internal', position: 'after' },
            { pattern: '@main/**', group: 'internal', position: 'after' },
          ],
          pathGroupsExcludedImportTypes: ['builtin'],
          'newlines-between': 'always',
          alphabetize: { order: 'asc', caseInsensitive: true },
        },
      ],
      'import/newline-after-import': ['error', { count: 1 }],
      'import/no-unresolved': 'off',

      // --- Imports: заборона циклів ---
      'import/no-cycle': ['error', { maxDepth: 5 }],

      // --- Imports: напрямок між шарами ---
      'boundaries/dependencies': [
        'error',
        {
          default: 'disallow',
          rules: [
            // bootstrap імпортує root і core
            { from: 'bootstrap', allow: ['root', 'core'] },
            // root (app.component, app.config) імпортує core і features
            { from: 'root', allow: ['core', 'feature'] },
            // features імпортують тільки core
            { from: 'feature', allow: ['core'] },
            // core нічого не імпортує з features чи root
            { from: 'core', allow: [] },
          ],
        },
      ],
    },
  },

  // ===================== Bootstrap entry point =====================
  {
    files: ['src/main.ts'],
    rules: {
      'no-console': 'off',
    },
  },

  // ===================== HTML files (Angular templates only) =====================
  {
    files: ['src/app/**/*.html'],
    languageOptions: { parser: angularTemplateParser },
    plugins: {
      '@angular-eslint/template': angularEslintTemplatePlugin,
      prettier: prettierPlugin,
    },
    rules: {
      'prettier/prettier': ['error', { printWidth: 80 }],
      '@angular-eslint/template/eqeqeq': 'error',
      '@angular-eslint/template/no-negated-async': 'error',
      '@angular-eslint/template/banana-in-box': 'error',
      '@angular-eslint/template/no-distracting-elements': 'error',
      '@angular-eslint/template/attributes-order': 'warn',
    },
  },
];
