/* 🤖 this file was generated by svg-to-ts */

export type lumenIcon = never;

export interface LumenIcon {
  name: lumenIcon;
  data: string;
}

export type LumenIconNameSubset<T extends Readonly<LumenIcon[]>> =
  T[number]['name'];

export const completeIconSet: LumenIcon[] = [];
